/*
 * Sample API
 *
 * Test optional primitive
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using MyNamespace.Api;
using MyNamespace.MySubset;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace MyNamespace.Test.Api
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    public sealed class DefaultApiTests : ApiTestsBase
    {
        private readonly IDefaultApi _instance;

        public DefaultApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IDefaultApi>();
        }

        /// <summary>
        /// Test GetOptionalAge
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetOptionalAgeAsyncTest()
        {
            var response = await _instance.GetOptionalAgeAsync();
            var model = response.Ok();
            Assert.IsType<OptionalPayload>(model);
        }

        /// <summary>
        /// Test GetRequiredAge
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetRequiredAgeAsyncTest()
        {
            var response = await _instance.GetRequiredAgeAsync();
            var model = response.Ok();
            Assert.IsType<RequiredPayload>(model);
        }
    }
}
