/*
 * Sample API
 *
 * Test optional primitive
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyNamespace.MySubset;
using MyNamespace.Client;
using System.Reflection;

namespace MyNamespace.Test.Model
{
    /// <summary>
    ///  Class for testing OptionalPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OptionalPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OptionalPayload
        //private OptionalPayload instance;

        public OptionalPayloadTests()
        {
            // TODO uncomment below to create an instance of OptionalPayload
            //instance = new OptionalPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OptionalPayload
        /// </summary>
        [Fact]
        public void OptionalPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" OptionalPayload
            //Assert.IsType<OptionalPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Age'
        /// </summary>
        [Fact]
        public void AgeTest()
        {
            // TODO unit test for the property 'Age'
        }
    }
}
